# Generated by Django 5.2.3 on 2025-07-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_id', models.CharField(max_length=10, unique=True, verbose_name='singer_id')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='singer_name')),
                ('profile', models.TextField(blank=True, null=True, verbose_name='singer_profile')),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='singer_image_url')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='singer_url')),
            ],
            options={
                'verbose_name': 'singer',
                'verbose_name_plural': 'singer',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=10, unique=True, verbose_name='song_id')),
                ('name', models.CharField(max_length=200, verbose_name='song_name')),
                ('cover', models.URLField(max_length=255, verbose_name='song_cover')),
                ('lyric', models.TextField(blank=True, null=True, verbose_name='song_lyric')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='song_url')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='data.singer', verbose_name='singer')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'song',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('content', models.TextField(verbose_name='content')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='time')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='data.song', verbose_name='song')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comment',
                'ordering': ['time'],
            },
        ),
    ]
